[package]
name = "symfind"
version = "0.1.0"
authors = ["jogn"]
edition = "2018"

[dependencies]
mach_object = "0.1.13"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
std = {default-features=false, features=["panic_immediate_abort"]}

